#!/bin/bash -eu

script -q -c './node_modules/.bin/karma start --single-run' |
    tee >(
        grep ✖ |
        grep -A 99999 'tests failed' |
        sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" > predicates-test.result)

dos2unix predicates-test.result
