name: CI Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
    - uses: actions/checkout@v2
    - uses: ianwalter/puppeteer-container@v4.0.0
      with:
        args: yarn test
